spring:
  application:
    name: t1

  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=t1;encrypt=false;trustServerCertificate=false;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:bd/tablas.sql
      data-locations: classpath:bd/data.sql

server:
  port: 8080
